CREATE TABLE FOOD (
	FOOD_NO	NUMBER	PRIMARY KEY,
	FOOD_NAME	VARCHAR2(100)	NULL,
	FOOD_ADDRESS	VARCHAR2(300)	NULL,
	FOOD_TYPE	VARCHAR2(50)	NULL,
	FOOD_OPENTIME	VARCHAR2(500)	NULL,
	FOOD_MENU	VARCHAR2(500)	NULL,
	FOOD_PHONE	VARCHAR2(50)	NULL,
	FOOD_ALLOW	NUMBER	NULL,
	FOOD_READCOUNT	NUMBER	NULL
);

ALTER TABLE FOOD ADD FOOD_readcount NUMBER DEFAULT '0';
ALTER TABLE food DROP COLUMN food_readcount;
SELECT * FROM FOOD LEFT JOIN MEMBER WHERE memberId=#{memberId};
SELECT * FROM MEMBER;



SELECT * FROM food;
SELECT * FROM food WHERE food_no=2995073;

INSERT INTO FOOD_HEART(fh_no,MEMBER_ID,FOOD_NO)
			VALUES(SEQ_FH_NO.NEXTVAL,MEMBER_ID,FOOD_NO);

SELECT * FROM food LEFT JOIN MEMBER using(fh_no) 
SELECT * FROM food LEFT JOIN MEMBER ON food.fh_no = MEMBER.fh_no WHERE MEMBER.member_id = #{member_id};

SELECT * FROM FOOD LEFT JOIN FOOD_PHOTO USING(FOOD_NO) 
				LEFT JOIN FOOD_HEART USING(FOOD_NO) ORDER BY FOOD_NO DESC;

SELECT * FROM food LEFT JOIN MEMBER USING (fh_no) WHERE MEMBER.member_id = #{member_id};


SELECT * FROM FOOD LEFT JOIN FOOD_PHOTO USING(FOOD_NO) ORDER BY FOOD_NAME ASC;
SELECT * FROM FOOD ORDER BY FOOD_NO DESC;
SELECT * FROM food;
--(FOOD_NO,FOOD_NAME,FOOD_ADDRESS,FOOD_TYPE,FOOD_OPENTIME,FOOD_MENU,FOOD_PHONE,FOOD_ALLOW,FOOD_READCOUNT)
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL,'연어상회','인천광역시','일식','10:00~11:00','연어초밥','010-111-111',11,11);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL,'홍콩반점','부산광역시','중식','11:00~12:00','짜장면','010-111-111',12,21);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL,'홍콩반점','인천광역시','일식','10:00~11:00','연어초밥','010-111-111',11,11);
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL,'홍콩반점','인천광역시','일식','10:00~11:00','연어초밥','010-111-111',11,11);
INSERT INTO FOOD_HEART values(seq_fh_no.nextval,'조장흠',);
SELECT * FROM FOOD_HEART;
SELECT FOOD_Name  FROM food WHERE food_name LIKE '%곤디%';
--맛집시퀀스생성
CREATE SEQUENCE SEQ_FOOD_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;
SELECT * FROM FOOD_HEART;
CREATE TABLE FOOD_PHOTO (
	FP_NO	NUMBER	PRIMARY KEY,
	FOOD_NO NUMBER REFERENCES FOOD(FOOD_NO) ON DELETE CASCADE,
	FP_NAME	VARCHAR2(100) NULL,
	FP_MAIN	VARCHAR2(100) NULL
);

CREATE SEQUENCE SEQ_FP_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE FOOD_REVIEW (
	FR_NO NUMBER PRIMARY KEY,
	FOOD_NO NUMBER REFERENCES FOOD(FOOD_NO) ON DELETE CASCADE,
	USER_ID	NUMBER	REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	FR_CONTENT VARCHAR2(500) NULL,
	FR_GRADE NUMBER NULL,
	FR_WRITE_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_FR_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE FOOD_HEART (
	FH_NO NUMBER PRIMARY KEY,
	MEMBER_ID NUMBER REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	FOOD_NO NUMBER REFERENCES FOOD(FOOD_NO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_FH_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE FOOD_REVIEW_PHOTO (
   RP_NO NUMBER PRIMARY key,
   FR_NO NUMBER REFERENCES FOOD_REVIEW(FR_NO) ON DELETE CASCADE,
   RP_NAME VARCHAR2(100) NULL
);

CREATE SEQUENCE SEQ_FRP_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;
SELECT * FROM FOOD LEFT JOIN FOOD_PHOTO USING(FOOD_NO) ORDER BY FOOD_NO DESC;
SELECT * FROM FOOD WHERE FOOD_NAME='백년짬뽕';

SELECT * FROM FOOD_REVIEW;
SELECT * FROM FOOD_REVIEW_PHOTO;
SELECT * FROM FOOD_HEART;
DELETE FROM FOOD WHERE FOOD_NAME='백년짬뽕';  

SELECT * FROM MEMBER;
SELECT * FROM FOOD_HEART;
INSERT INTO FOOD_HEART VALUES(3,11,52);

SELECT f.*,(SELECT COUNT(*) FROM FOOD_HEART WHERE FOOD_NO=f.FOOD_NO) AS FOOD_HEART FROM FOOD f;

SELECT * FROM ACCOMMODATION;
SELECT * FROM AC_HEART;

SELECT * FROM ACCOMMODATION a ;
SELECT a.*,(SELECT AVG(AR_GRADE)FROM AC_REVIEW b WHERE a.AC_ID=ßb.AC_ID)REVIEWGRADE FROM ACCOMMODATION a;   
SELECT a.*,f.*,
		(SELECT AVG(AR_GRADE)FROM AC_REVIEW r WHERE a.AC_ID=r.AC_ID)REVIEWGRADE 
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE f ON a.AC_ID=f.AC_ID ;

UPDATE food SET likeCount = likeCount + 1 WHERE member_Id = #{member_Id};

SELECT * FROM FOOD_HEART;

SELECT * FROM MEMBER;

UPDATE FOOD_HEART SET FH_NO = FH_NO - 1 WHERE member_Id = 'member_id';

UPDATE FOOD_HEART SET FH_NO = FH_NO + 1 WHERE member_Id = 'member_id';

UPDATE FOOD_HEART SET FH_NO = CASE WHEN FH_NO > 0 THEN FH_NO - 1 ELSE 0 END WHERE member_Id = 'member_id';

SELECT * FROM TOURIS;
