SELECT * FROM FOOD 
RIGHT OUTER JOIN FOOD_REVIEW USING(FOOD_NO) 
LEFT OUTER JOIN FOOD_REVIEW_PHOTO USING(FR_NO)  
LEFT OUTER JOIN MEMBER USING(MEMBER_ID) 
WHERE MEMBER_ID = 44 ORDER BY FR_WRITE_DATE DESC;

SELECT * FROM ACCOMMODATION a 
JOIN AC_HEART ah USING(ac_id) WHERE member_id=44;

SELECT * FROM FOOD_PHOTO  WHERE FOOD_NO = 1269536;

SELECT * FROM FOOD_PHOTO WHERE FP_NAME = 'http://tong.visitkorea.or.kr/cms/resource/18/2998218_image2_1.jpg';
DELETE FROM FOOD WHERE FOOD_NO = 2998217;


SELECT * FROM FOOD_review ;
SELECT * FROM FOOD_PHOTO WHERE FOOD_NO = 2901202;



MERGE INTO FOOD_PHOTO F
			  USING FOOD_PHOTO_TEMP T
				 ON (F.FP_ID = T.FP_ID)
			  WHEN NOT MATCHED THEN
			  	 INSERT(FP_NO,FOOD_NO,FP_NAME,FP_MAIN,FP_ID)
			   	 VALUES(T.FP_NO,T.FOOD_NO,T.FP_NAME,T.FP_MAIN,T.FP_ID);

UPDATE FOOD_Photo SET
				FP_NAME=#{fpName},
				FP_MAIN=#{fpMain},
				FP_ID=#{fpId}
			WHERE FP_NAME = #{fpName}
			
INSERT INTO FOOD_PHOTO VALUES(
		SEQ_FP_NO.NEXTVAL,2901202,
		'http://tong.visitkorea.or.kr/cms/resource/94/2901194_image2_1.jpg',
	0,'http://tong.visitkorea.or.kr/cms/resource/94/2901194_image2_1.jpg');

INSERT INTO FOOD_PHOTO VALUES(
			SEQ_FP_NO.NEXTVAL,2870486,
			'http://tong.visitkorea.or.kr/cms/resource/73/2870473_image2_1.jpg',0,
			'http://tong.visitkorea.or.kr/cms/resource/73/2870473_image2_1.jpg');

SELECT count(*) FROM FOOD;
SELECT * FROM FOOD;
SELECT * FROM FOOD_temp;
SELECT * FROM FOOD_BLACK_LIST fbl ;
DELETE FROM FOOD;
DELETE FROM FOOD_temp;
DELETE FROM FOOD_PHOTO;
DELETE FROM FOOD_PHOTO_TEMP;


INSERT INTO FOOD_TEMP SELECT * FROM FOOD WHERE FOOD_NO = 2788416;


SELECT * FROM FOOD LEFT OUTER JOIN FOOD_PHOTO USING(FOOD_NO) WHERE ROWNUM <= 50;


SELECT * FROM FOOD_temp WHERE EXISTS (SELECT FOOD_NO FROM FOOD_temp);
SELECT * FROM FOOD_PHOTO;
DELETE FROM FOOD_PHOTO;
ALTER TABLE FOOD_PHOTO ADD FP_ID VARCHAR2(100) NULL;

SELECT * FROM FOOD_PHOTO_TEMP;
DELETE FROM FOOD_PHOTO_TEMP;
ALTER TABLE FOOD_PHOTO_TEMP ADD FP_ID VARCHAR2(100) NULL;

SELECT COUNT(*) FROM FOOD_temp;

MERGE INTO FOOD_PHOTO F
			  USING FOOD_PHOTO_TEMP T
				 ON (F.FP_ID = T.FP_ID)
			  WHEN MATCHED THEN
				 UPDATE SET	F.FP_NAME = T.FP_NAME
				   		  , F.FP_MAIN = T.FP_MAIN
			  WHEN NOT MATCHED THEN
			  	 INSERT(FP_NO,FOOD_NO,FP_NAME,FP_MAIN,FP_ID)
			   	 VALUES(SEQ_FP_NO.NEXTVAL,T.FOOD_NO,T.FP_NAME,T.FP_MAIN,T.FP_ID)
			   	 ;
			   	 
SELECT FOOD_MENU FROM FOOD WHERE FOOD_NO = 2788416;

SELECT * FROM FOOD_REVIEW LEFT OUTER JOIN FOOD_REVIEW_PHOTO USING(FR_NO) WHERE FR_NO = 29;
 
SELECT * FROM FOOD_REVIEW;

SELECT * FROM FOOD_REVIEW_PHOTO;

SELECT * FROM FOOD_REVIEW WHERE FR_NO = 34;
DELETE FROM FOOD_REVIEW WHERE FOOD_NO = 2998578; 

SELECT * FROM FOOD_REVIEW_PHOTO WHERE FR_NO = 29;

DELETE FROM "FOOD_REVIEW" FR
WHERE EXISTS (
SELECT 1 FROM "FOOD_REVIEW_PHOTO" FRP WHERE FR.FR_NO = FRP.FR_NO
)
AND FR.FR_NO = 34;

DELETE FROM FOOD_REVIEW WHERE FR_NO = 34;

SELECT count(*) FROM FOOD_REVIEW_PHOTO WHERE FR_NO = 36;
DELETE FROM FOOD_REVIEW_PHOTO WHERE FR_NO = 34;
