CREATE TABLE FOOD (
	FOOD_NO	NUMBER	PRIMARY KEY,
	FOOD_NAME	VARCHAR2(100)	NULL,
	FOOD_ADDRESS	VARCHAR2(300)	NULL,
	FOOD_TYPE	VARCHAR2(50)	NULL,
	FOOD_OPENTIME	VARCHAR2(500)	NULL,
	FOOD_MENU	VARCHAR2(500)	NULL,
	FOOD_PHONE	VARCHAR2(50)	NULL,
	FOOD_ALLOW	NUMBER	NULL,
	FOOD_READCOUNT	NUMBER	NULL
);
SELECT * FROM food;
--(FOOD_NO,FOOD_NAME,FOOD_ADDRESS,FOOD_TYPE,FOOD_OPENTIME,FOOD_MENU,FOOD_PHONE,FOOD_ALLOW,FOOD_READCOUNT)
INSERT INTO FOOD VALUES(SEQ_FOOD_NO.NEXTVAL,'초밥','서울특별시','초반','초반','초반','초반',1,1);
--맛집시퀀스생성
CREATE SEQUENCE SEQ_FOOD_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE FOOD_PHOTO (
	FP_NO	NUMBER	PRIMARY KEY,
	FOOD_NO NUMBER REFERENCES FOOD(FOOD_NO) ON DELETE CASCADE,
	FP_NAME	VARCHAR2(100) NULL,
	FP_MAIN	VARCHAR2(100) NULL
);

CREATE SEQUENCE SEQ_FP_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE FOOD_REVIEW (
	FR_NO NUMBER PRIMARY KEY,
	FOOD_NO NUMBER REFERENCES FOOD(FOOD_NO) ON DELETE CASCADE,
	USER_ID	NUMBER	REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	FR_CONTENT VARCHAR2(500) NULL,
	FR_GRADE NUMBER NULL,
	FR_WRITE_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_FR_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE FOOD_HEART (
	FH_NO NUMBER PRIMARY KEY,
	MEMBER_ID NUMBER REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE,
	FOOD_NO NUMBER REFERENCES FOOD(FOOD_NO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_FH_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE FOOD_REVIEW_PHOTO (
   RP_NO NUMBER PRIMARY key,
   FR_NO NUMBER REFERENCES FOOD_REVIEW(FR_NO) ON DELETE CASCADE,
   RP_NAME VARCHAR2(100) NULL
);

CREATE SEQUENCE SEQ_FRP_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

SELECT * FROM FOOD;
SELECT * FROM FOOD_PHOTO;
SELECT * FROM FOOD_REVIEW;
SELECT * FROM FOOD_REVIEW_PHOTO;
SELECT * FROM FOOD_HEART;