<<<<<<< HEAD
		SELECT *
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE USING(AC_ID)
		LEFT JOIN AC_PAY USING(AC_ID)
		LEFT JOIN AC_REVIEW r USING(AC_ID)
		LEFT JOIN MEMBER m ON r.MEMBER_ID =m.MEMBER_ID  
		LEFT JOIN AR_FILE USING(AR_ID)
		LEFT JOIN AC_FACILITIES USING(AC_ID)
		LEFT JOIN AFA_LIST USING(AFA_ID)
		WHERE AC_ID=5
		ORDER BY AF_MAIN_YN DESC
		;
	
		SELECT *
		FROM ACCOMMODATION
		LEFT JOIN AC_REVIEW USING(AC_ID)
		LEFT JOIN MEMBER USING(MEMBER_ID)
		WHERE AC_ID=5;
		
		
	SELECT * FROM "MEMBER" m ;
	SELECT * FROM AC_REVIEW ar ;
	
	SELECT a.*,(SELECT COUNT(*) FROM AC_REVIEW WHERE AC_ID=a.AC_ID)REVIEWCOUNT,
	(SELECT AVG(AR_GRADE)FROM AC_REVIEW r WHERE a.AC_ID=r.AC_ID)REVIEWGRADE  
	FROM ACCOMMODATION a WHERE AC_ID =5;
	
SELECT a.*,f.*,
		(SELECT AVG(AR_GRADE)FROM AC_REVIEW r WHERE a.AC_ID=r.AC_ID)REVIEWGRADE 
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE f ON a.AC_ID=f.AC_ID ;		
	
	SELECT a.*,f.*,
		(SELECT COUNT(*) FROM AC_REVIEW WHERE AC_ID=a.AC_ID)REVIEWCOUNT,
		(SELECT AVG(AR_GRADE)FROM AC_REVIEW r WHERE a.AC_ID=r.AC_ID)REVIEWGRADE  
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE f ON a.AC_ID=f.AC_ID
		WHERE a.AC_ID =5;
		
SELECT*FROM MEMBER;

		SELECT *
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE USING(AC_ID)
		LEFT JOIN AC_HEART USING(AC_ID)
		LEFT JOIN AC_REVIEW r USING(AC_ID)
		LEFT JOIN AC_RESERVATION USING(AC_ID)
		LEFT JOIN MEMBER m ON r.MEMBER_ID =m.MEMBER_ID
		LEFT JOIN AR_FILE USING(AR_ID)
		LEFT JOIN AC_FACILITIES USING(AC_ID)
		LEFT JOIN AFA_LIST
		USING(AFA_ID)
		WHERE AC_ID=8
		ORDER BY AF_MAIN_YN DESC;
	
	SELECT a.*,f.*,h.*,
		(SELECT AVG(AR_GRADE)FROM AC_REVIEW r WHERE
		a.AC_ID=r.AC_ID)REVIEWGRADE
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE f ON
		a.AC_ID=f.AC_ID
		LEFT JOIN AC_RESERVATION ar ON a.AC_ID=ar.AC_ID
		LEFT JOIN AC_HEART h ON a.AC_ID=h.AC_ID
		WHERE
		1=1;
	
	SELECT * FROM ACCOMMODATION
		LEFT JOIN AC_FILE USING(AC_ID)
		LEFT JOIN
		AC_FACILITIES USING(AC_ID)
		LEFT JOIN AFA_LIST USING(AFA_ID)
		WHERE
		AC_ID=44;
	
SELECT * FROM AC_FILE WHERE AC_ID=45;
SELECT * FROM AFA_LIST al ;
SELECT * FROM AC_FACILITIES af  LEFT JOIN AFA_LIST USING(AFA_ID) WHERE AC_ID =47;
SELECT * FROM  AFA_LIST al WHERE AFA_ID =20;
SELECT * FROM AC_FACILITIES af WHERE AC_ID=47;
SELECT * FROM AFA_LIST al WHERE AFA_ID=20;

SELECT * FROM MEMBER;

SELECT a.*,f.*,h.*,ar.*,
		(SELECT AVG(AR_GRADE)FROM AC_REVIEW r WHERE
		a.AC_ID=r.AC_ID)REVIEWGRADE
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE f ON
		a.AC_ID=f.AC_ID
		LEFT JOIN AC_RESERVATION ar ON a.AC_ID=ar.AC_ID
		LEFT
		JOIN AC_HEART h ON a.AC_ID=h.AC_ID
		WHERE
		1=1;
		
SELECT * FROM AC_PAY ap ;

	SELECT *
		FROM AC_PAY
		JOIN ACCOMMODATION USING(AC_ID)
		JOIN MEMBER USING(MEMBER_ID)
		JOIN AC_FILE USING(AC_ID)
		JOIN AC_RESERVATION USING(AP_ID)
		WHERE MEMBER_ID=42
		ORDER BY AP_DATE DESC;
		
SELECT a.*,f.*,h.*,ar.*,
		(SELECT AVG(AR_GRADE)FROM AC_REVIEW r WHERE
		a.AC_ID=r.AC_ID)REVIEWGRADE
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE f ON a.AC_ID=f.AC_ID
		LEFT JOIN AC_RESERVATION ar ON a.AC_ID=ar.AC_ID
		LEFT JOIN AC_HEART h ON a.AC_ID=h.AC_ID
		WHERE
		1=1
--			AND AC_ADDRESS LIKE '%서%'
			AND NOT ((CHECKIN >= '2023-08-16' AND CHECKIN <= '2023-08-18') OR (CHECKOUT >= '2023-08-16' AND CHECKOUT<='2023-08-18'))
			AND AC_PEOPLE >= 1
		ORDER BY AC_DATE DESC;	
		
	UPDATE AC_RESERVATION SET CHECKIN ='2023-08-15',CHECKOUT ='2023-08-18' WHERE ARV_ID =194;
	SELECT * FROM AC_RESERVATION ar ;
	
SELECT a.*,f.*,h.*,
(SELECT AVG(AR_GRADE)FROM AC_REVIEW r WHERE
a.AC_ID=r.AC_ID)REVIEWGRADE 
FROM ACCOMMODATION a
LEFT JOIN AC_FILE f ON a.AC_ID=f.AC_ID
LEFT JOIN AC_HEART h ON a.AC_ID=h.AC_ID
where 1=1
AND AC_ADDRESS LIKE '%서%'
AND AC_PEOPLE >= 1
AND a.ac_id not in (
SELECT ac_id FROM ac_reservation
WHERE ('23/08/16'>=CHECKIN AND CHECKOUT >= '23/08/16'
OR '23/08/20'>=CHECKIN AND CHECKOUT >= '23/08/20'))ORDER BY AC_DATE DESC;	
        SELECT * FROM MEMBER;
	
       SELECT * FROM AC_RESERVATION ar;
       SELECT * FROM ac_pay;
      INSERT INTO
		AC_RESERVATION
		VALUES
		(SEQ_ARV_NO.NEXTVAL,
		67,NULL,TO_DATE('2023-09-18','YYYY-MM-DD'),TO_DATE('2023-09-20','YYYY-MM-DD'));
		
	SELECT * FROM AC_PAY ap ;
	SELECT  * FROM AP_REFUND ar ;
UPDATE AC_PAY SET AP_CANCEL_DATE=SYSDATE WHERE AP_CANCEL !='N';
	ALTER TABLE AC_PAY ADD AP_CANCEL_DATE DATE;
SELECT COUNT(*) FROM
		AC_PAY WHERE AP_CANCEL='T' OR AP_CANCEL='F';
	
	ALTER TABLE AP_REFUND  MODIFY (APR_CONTENT  NULL);
		
	UPDATE AC_PAY SET AP_CANCEL ='R' WHERE AP_ORDER_ID ='K2023081639786901';
	
SELECT * FROM AC_PAY
		JOIN ACCOMMODATION USING(AC_ID)
		JOIN MEMBER USING(MEMBER_ID)
		JOIN AC_RESERVATION USING(AP_ID)
		LEFT JOIN AP_REFUND USING(AP_ID)
		ORDER BY AP_DATE DESC;
		
	SELECT * FROM ACCOMMODATION a JOIN AC_HEART ah USING(ac_id) WHERE member_id='42';
	SELECT * FROM AC_PAY ap ;
UPDATE AC_RESERVATION SET CHECKIN ='2023-08-01',CHECKOUT ='2023-08-30' WHERE AP_ID =90;

SELECT * FROM food LEFT JOIN  food_heart using(food_no);
SELECT * FROM FOOD_HEART fh ;
SELECT * FROM FOOD LEFT JOIN FOOD_PHOTO USING(FOOD_NO) 
         left join food_heart using(Food_no)
         ORDER BY FOOD_NO DESC;
        
        SELECT * FROM TOURIS_HEART LEFT JOIN TOURIS USING(TOURIS_ID) WHERE MEMBER_ID = 42;
