		SELECT *
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE USING(AC_ID)
		LEFT JOIN AC_PAY USING(AC_ID)
		LEFT JOIN AC_REVIEW r USING(AC_ID)
		LEFT JOIN MEMBER m ON r.MEMBER_ID =m.MEMBER_ID  
		LEFT JOIN AR_FILE USING(AR_ID)
		LEFT JOIN AC_FACILITIES USING(AC_ID)
		LEFT JOIN AFA_LIST USING(AFA_ID)
		WHERE AC_ID=5
		ORDER BY AF_MAIN_YN DESC
		;
	
		SELECT *
		FROM ACCOMMODATION
		LEFT JOIN AC_REVIEW USING(AC_ID)
		LEFT JOIN MEMBER USING(MEMBER_ID)
		WHERE AC_ID=5;
		
		
	SELECT * FROM "MEMBER" m ;
	SELECT * FROM AC_REVIEW ar ;