SELECT * FROM ACCOMMODATION a ;
SELECT a.*,(SELECT AVG(AR_GRADE)FROM AC_REVIEW b WHERE a.AC_ID=ßb.AC_ID)REVIEWGRADE FROM ACCOMMODATION a;   
SELECT a.*,f.*,
		(SELECT AVG(AR_GRADE)FROM AC_REVIEW r WHERE a.AC_ID=r.AC_ID)REVIEWGRADE 
		FROM ACCOMMODATION a
		LEFT JOIN AC_FILE f ON a.AC_ID=f.AC_ID ;